runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest
env_variables:

handlers:
- url: /blobstore.*
  script: blobstore.app
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
